### ISSUE TITLE
Проверьте, пожалуйста, мой проект

### ISSUE THREAD

**Issue by katorina** [katorina/TelephoneBook#10]

**Comment by JohnKhandygo** [comment]
На будущее: пишите, что задание готово к проверке в комментариях к соответствующему issue. Например, Вы исправили какое-то из замечаний, можете в комментарии к этому замечанию написать, что он исправлен, можно проверять. Когда Вы пишите комментарий к issue я сразу получилось уведомление на почту. Так мне, с одной стороны, не надо разбираться, что именно было исправлено, а Вы можете исправлять замечания по одному за раз.
