### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/TelephoneBook#11]
Вам осталось исправить совсем чуть-чуть, поэтому высылаю второей задание.

**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**tail**
Выделение из текстового файла его конца некоторого размера:
fileN задаёт имя входного файла. Если параметр отсутствует, следует считывать входные данные с консольного ввода. Если параметров несколько, то перед выводом для каждого файла следует вывести его имя в отдельной строке.
Флаг -o ofile задаёт имя выходного файла (в данном случае ofile). Если параметр отсутствует, следует выводить результат на консольный вывод.
Флаг -с num, где num это целое число, говорит о том, что из файла нужно извлечь последние num символов.
Флаг -n num, где num это целое число, говорит о том, что из файла нужно извлечь последние num строк.

Command line: tail [-c num|-n num] [-o ofile] file0 file1 file2 …

В случае, когда какое-нибудь из имён файлов неверно или указаны одновременно флаги -c и -n, следует выдать ошибку. Если ни один из этих флагов не указан, следует вывести последние 10 строк.

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки и запуска разработанного приложения из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Comment by JohnKhandygo** [comment]
Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 


Собственно после готовности первого этапа можно начинать проверку.

**Comment by katorina** [comment]
https://github.com/katorina/Tail

**Comment by JohnKhandygo** [comment]
Перенес описание задания в соответствующий репозиторий. Все замечания будут появляться там.
