### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/TelephoneBook#7]
- [x] Вашу программу не получится использовать извне как библиотеку из-за использованных модификаторов области видимости для разработанных классов и методов в них.  
- [x] Если значения полей не меняются, стоит использовать модификатор `final` при их объявлении. Это позволяет избавиться от достаточно дурацких ошибок. 
- [x] Либо метод `TelephoneBook::addUser` реализован некорректно, либо все остальные методы в `TelephoneBook` не учитывают того, что в списке `users` может быть несколько контактов с одинаковым номером.
- [x] Метод `TelephoneBook::addUser` допускает добавление контактов с разными именами, но одинаковыми номерами.
- [x] Для того, чтобы воспользоваться методом `TelephoneBook::deleteUser`, мне надо сконструировать целый объект `User` (а ведь ему может соответствовать несколько номеров). К тому же, Вы не реализовали `equals` в классе `User`, так что воспользоваться этой функцией становится почти невозможно. 
- [x] Подумайте, может ли метод `User::getNumbers` каким-либо образом "сломать" Вашу реализацию. Если да, то как?
- [x] В методе `User::transformNumber` много ошибок. 
  - Для того, чтобы проверить, соответствует ли строка регулярном выражению существует метод [matches](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#matches(java.lang.String)). Делать это через `replaceAll` просто верх безумства.
  - В коде не должно быть вызовов `System.out.println`. Если Вам необходимо логирование действий программы, то стоит использовать специальные библиотеки. Если Вам необходимо отладить программу, для этого существует специальный режим запуска программы --- [debug](https://www.jetbrains.com/help/idea/debugging.html).
  - В принципе изменение номера --- не самая лучшая идея. Как пользователь, я бы ожидал, что приписав некий номер контакту, я могу использовать этот же самый номер для того, чтобы найти соответствующий контакт, однако в `TelephoneBook` Вы не поддерживаете преобразование номеров. 
  - Если формат номера некорректен, то получаем в телефонной книге запись с номером `null`. С точки зрения логики это как-то совсем неправильно.
   - Формат номера, который Вы придумали не совсем правильный. После `#` может идти добавочный номер (то есть последовательность только цифр). Если символ `#` присутствует в номере, то он должен быть единственным. Символы `+` и `*` могут стоять только в самом начале номера и нигде больше, при этом только один из этих символов. Замена `8` на `+7` --- Тоже спорная затея, однако это можно оставить. 
  Учитывая все вышесказанное, я бы предложил следующий алгоритм: убрать из `number` все `-`, проверить формат полученной строки и, если все хорошо, то добавлять номер без `-` в книгу. Если все плохо, то надо что-то придумать, но точно не `null` возвращать.  
- [x] Метод `User::addNumber` реализован крайне странно. Вы же можете проверить наличие такого же номера до того, как добавлять его.
- [x] Вообще в задании нигде не сказано, что не может быть контакта без номеров. Если Вам это по какой-то причине кажется неприемлемым, значит это должно быть как-то доступно для пользователя Вашей билиотекой, Вы же просто игнорируете запрос на удаление номера, пользователь не знает, что Вы ничего не удалили и причин этого тоже не знает.
- [x] Методы `User::addNumber` и `User:deleteNumber` используются только в тестах. Они точно Вам нужны?
- [x] Методы, изменяющие `User` и `TelephoneBook` не дают возможности программно узнать, были ли в действительности произведены какие-либо изменения (например, был ли пользователь действительно удален или его просто не существовало).
- [x] В классах `TelephoneBook` и `User` отсутствуют реализации методов `toString`, `equals` и `hashCode`.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками из предыдущего коментария актуально. 
- [x] Метод `User::transformNumber` не допускает наличия добавочного номера после `#`. 
- [x] Не понял, зачем в `User::transformNumber` вся этот цикл с вложенным `switch`. Единственность и корректность позиционирования символов  `+`, `*` и `#` гарантируется регулярным выражением, разве не так?
- [x] В методе `User::transformNumber` Вы в конце концов, если все хорошо, возвращаете сам `number`. С чего бы тогда этот метод называется `transform`, если он ничего не трансформирует на самом деле? 
  Здесь, видимо, произошло недопонимание, поскольку я, видя название `tranformNumber` (Вы сейчас должны понять, почему так важно именовать методы и поля правильно), предполагаю, что этот метод должен преобразовать номер (например, выкинуть из него ненужные символы) для того, чтобы затем хранить уже этот преобразованный номер. Вы же, кажется, используете этот метод для того, чтобы проверить, корректен ли формат номера. Ну так и назовите его соответствующее, если так. И пусть тогда `boolean` возвращает.
- [x] Методы, изменяющие `TelephoneBook` не дают возможности программно узнать, были ли в действительности произведены какие-либо изменения (например, был ли пользователь действительно удален или его просто не существовало).
- [x] В классе `TelephoneBook` отсутствуют реализации методов `toString`, `equals` и `hashCode`.

**Comment by katorina** [comment]
Вроде, всё предусмотрела, за исключением комментариев по поводу возможного наличия у разных контактов одинаковых номеров.
И я не понимаю, как быть без методов User:deleteNumber и User::addNumber

**Comment by katorina** [comment]
Вроде как подправила регулярное выражение для номера, теперь оно допускает наличие добавочного номера через #.

> Вообще в задании нигде не сказано, что не может быть контакта без номеров.

Программа допускает удаление единственного номера у контакта.

> Методы, изменяющие TelephoneBook не дают возможности программно узнать, были ли в действительности произведены какие-либо изменения (например, был ли пользователь действительно удален или его просто не существовало).

Метод deleteUser возвращает true/false. То есть, если такой контакт был и его удаляют - возвращаем true, а если такого контакта не было вовсе или, например, некорректно введено имя, то возвращаем false.

> Подумайте, может ли метод User::getNumbers каким-либо образом "сломать" Вашу реализацию. Если да, то как?

Метод User::getNumbers допускает возможность вернуть пустой ArrayList, если у контакта нет ни одного номера - при обращении, мы получим null. (Других идей нет)

> Либо метод TelephoneBook::addUser реализован некорректно, либо все остальные методы в TelephoneBook не учитывают того, что в списке users может быть несколько контактов с одинаковым номером.

Тут тоже не совсем понятно, просто если одинаковые номера будут у разных контактов, то это многое меняет и не совсем понятно, как это все реализовывать..

**Comment by katorina** [comment]
Можно спросить, есть ли у меня сейчас оценка "3"?.. И если да, то что нужно сделать для оценки "4".
Просто я немного переживаю за дедлайн по второму проекту.

**Comment by JohnKhandygo** [comment]
Для удобства переписываю все оставшиеся замечания сюда. 

- [x] Либо метод `TelephoneBook::addUser` реализован некорректно, либо все остальные методы в `TelephoneBook` не учитывают того, что в списке `users` может быть несколько контактов с одинаковым номером.
- [x] Метод `TelephoneBook::addUser` допускает добавление контактов с разными именами, но одинаковыми номерами.
- [x] Для того, чтобы воспользоваться методом `TelephoneBook::deleteUser`, мне надо сконструировать целый объект `User`. Я вижу, как Вы предполагаете использовать этот метод (из тестов), но обычно это делается несколько проще. 
- [x] Подумайте, может ли метод `User::getNumbers` каким-либо образом "сломать" Вашу реализацию. Если да, то как?
- [ ] Методы, изменяющие `TelephoneBook` не дают возможности программно узнать, были ли в действительности произведены какие-либо изменения (например, был ли пользователь действительно удален или его просто не существовало).
- [x] Мне, а значит и Вам тоже, idea подсвечивает регулряное выражение в `User::checkNumber` красным (потому что там ошибка). Из-за этого даже тесты сейчас не запускаются.

**Comment by katorina** [comment]
Вроде всё.
Насчет getNumbers(): раньше возвращаемый список можно было изменить извне, а теперь возвращается копия оригинального массива.
