### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/TelephoneBook#8]
- [x] Все тестовые сценарии лучше разделить на два класса: один для тестирования `User` (`UserTest`), другой для `TelephoneBook` (`TelephoneBookTest`). Таким образом логику тестов будет легче понять.
- [x] В тестах много лишних assert'ов. Не надо проверять корректность функционирования тех методов, которые уже были протестированы. Так, например, тестовый метод `addNumber` по сути не нужен, поскольку Вы уже покрыли корректность функционирования этого сценария в функциях `searchByName_and_GetNumbers` и `searchByNumber_and_GetName`.
- [x] Тесты не покрывают случаи, когда в телефонной книге существует контакт с несколькими номерами.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками из предыдущего комментария, актуально.
- [x] А с чего бы это в `UserTest` фигурирует экземпляр `TelephoneBook`? Вы же в этом методе проверяете корректность функционирования именно класса `User`. Самого по себе.

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками из предыдущих комментариев, актуально.

- [x] Ну и зачем Вам несколько пользователей в тесте на пользователей? Зачем так сложно-то? Вам просто надо показать, что все публичные методы работают корректно.

**Comment by katorina** [comment]
Посмотрите тесты, пожалуйста

**Comment by JohnKhandygo** [comment]
Почти.

> Тесты не покрывают случаи, когда в телефонной книге существует контакт с несколькими номерами.

Мне надоело давать Вам намеки) Что будет, если я напишу примерно такой тест?
```
book = new TelephoneBook();
book.addUser("name", "898727");
book.addUser("name", "565919");
final User found = book.searchByName("name")
assertEquals(new ArrayList<String>("898727", "565919"), found.getNumbers())
```
